# Generated by Django 3.1.5 on 2021-02-07 23:28

import datetime
from django.db import migrations, models
import django.db.models.deletion
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='category names')),
                ('index', models.IntegerField(default=99, verbose_name='category index')),
                ('icon', models.CharField(default='fa-home', max_length=30, verbose_name='icon')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='tag name')),
            ],
            options={
                'verbose_name': 'tag name',
                'verbose_name_plural': 'tag names',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='article Title')),
                ('desc', models.TextField(max_length=100, verbose_name='article Description')),
                ('content', mdeditor.fields.MDTextField(verbose_name='article content')),
                ('click_count', models.IntegerField(default=0, verbose_name='click count')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='post time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='update time')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.category', verbose_name='category names')),
                ('tag', models.ManyToManyField(to='blog.Tag', verbose_name='tag names')),
            ],
            options={
                'verbose_name': 'article',
                'verbose_name_plural': 'articles',
            },
        ),
    ]
